#!/usr/bin/env perl
use strict;
use warnings;
use v5.16;

use FindBin;
use lib (
    "$FindBin::Bin/lib",           # Deployed: threads -> lib/Threads/
    "$FindBin::Bin/../perl/lib",   # Source repo: shell/threads -> perl/lib/Threads/
);

use Threads::CLI;

exit Threads::CLI->run(@ARGV);
